apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          imagePullPolicy: Always
          image: shahincsejnu/gocom-auth:a7a4b0a
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: server
